# Generated by Django 5.1.5 on 2025-01-18 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_healthconditionsindexpage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthconditionsindexpage',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='HealthConditionPage',
        ),
        migrations.DeleteModel(
            name='HealthConditionsIndexPage',
        ),
    ]
