# Generated by Django 5.1.5 on 2025-01-18 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_healthcondition'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HealthCondition',
        ),
    ]
