# Generated by Django 5.1.5 on 2025-01-20 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='cause',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='prevention',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='symptoms',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='treatment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
