# Generated by Django 5.1.5 on 2025-01-21 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_topic_cause_topic_prevention_topic_symptoms_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='cause',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='description',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='prevention',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='symptoms',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='treatment',
        ),
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
