# Generated by Django 5.1.5 on 2025-01-21 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_sliderimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SliderImage',
        ),
    ]
